version: '3'

services:
  postgresql:
    image: postgres:${POSTGRES_VERSION:-13.4}
    restart: always
    hostname: postgresql
    command: postgres -c 'max_connections=200'
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./src/db/postgres/db-init-scripts:/docker-entrypoint-initdb.d:rw
      - ./target/tmp/data/postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=superuser-passswd