version: '3'

services:
  postgresql:
    image: postgres:${POSTGRES_VERSION:-13.1}
    restart: always
    hostname: postgresql
    command: postgres -c 'max_connections=200'
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src/db/postgres/db-init-scripts:/docker-entrypoint-initdb.d:rw
      - ./tmp/data/postgres:/var/lib/postgresql/data:rw