CREATE USER seq with PASSWORD 'seq01';

CREATE DATABASE dev_seq;

GRANT pg_read_server_files TO seq;
ALTER ROLE seq NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;

ALTER DATABASE dev_seq OWNER TO seq;