CREATE TABLE IF NOT EXISTS SQ_MERCHANT(

id         BIGINT          NOT NULL,
name       VARCHAR(255)    NOT NULL,
email      VARCHAR(255)    NOT NULL,
cif        VARCHAR(10)     NOT NULL,

CONSTRAINT PK_SQ_MERCHANT PRIMARY KEY (ID)
);