CREATE TABLE IF NOT EXISTS SQ_SHOPPER(

id         BIGINT          NOT NULL,
name       VARCHAR(255)    NOT NULL,
email      VARCHAR(255)    NOT NULL,
nif        VARCHAR(10)     NOT NULL,

CONSTRAINT PK_SQ_SHOPPER PRIMARY KEY (ID)
);