CREATE SEQUENCE IF NOT EXISTS SEQ_SQ_DISBURSEMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_SQ_ORDER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_SQ_SHOPPER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_SQ_MERCHANT_ID START WITH 1 INCREMENT BY 1;